### ISSUE TITLE
Prisma ERD generator fails out of nothing suddenly. Worked before.

### ISSUE THREAD

**Issue by maakle** [keonik/prisma-erd-generator#145] opened 2022-10-27 04:02 UTC
The generator fails with the following output:

```
mathiasklenk@passbase lucid % npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
data model written to /Users/mathiasklenk/Developer/lucid/prisma/debug/1-datamodel.json
applied @map to fields written to /Users/mathiasklenk/Developer/lucid/prisma/debug/2-datamodel-map-applied.json
mermaid written to /Users/mathiasklenk/Developer/lucid/prisma/debug/3-mermaid.mmd
mermaid command:  /Users/mathiasklenk/Developer/lucid/node_modules/.bin/mmdc -i /var/folders/qs/nv116z_51jv54p5lp4bx4vm80000gn/T/prisma-erd-JhnaHt/prisma.mmd -o /Users/mathiasklenk/Developer/lucid/prisma/ERD.svg -t forest -c /var/folders/qs/nv116z_51jv54p5lp4bx4vm80000gn/T/prisma-erd-JhnaHt/config.json
Error: 
✔ Generated Prisma Client (4.5.0 | library) to ./node_modules/@prisma/client in 159ms

Command failed: /Users/mathiasklenk/Developer/lucid/node_modules/.bin/mmdc -i /var/folders/qs/nv116z_51jv54p5lp4bx4vm80000gn/T/prisma-erd-JhnaHt/prisma.mmd -o /Users/mathiasklenk/Developer/lucid/prisma/ERD.svg -t forest -c /var/folders/qs/nv116z_51jv54p5lp4bx4vm80000gn/T/prisma-erd-JhnaHt/config.json
```

I have it setup like this in my `schema.prisma` file:

```
generator erd {
  provider = "prisma-erd-generator"
  output   = "./ERD.svg"
  erdDebug = true
}
```

I'm using `"prisma-erd-generator": "^1.2.1"` and `"@mermaid-js/mermaid-cli": "^9.1.7"` in my package.json. Is this a known bug or anything I am doing wrong?

**Comment by jferrettiboke** [comment] 2022-10-31 15:21
Yeah. I can confirm `prisma-erd-generator` breaks with Prisma 4.5.0.

**Comment by keonik** [comment] 2022-10-31 19:27
Hoping the latest release updating dependencies fixed it 🤞🏼 checking now. Just released a version with 4.5 prisma

**Comment by keonik** [comment] 2022-10-31 19:38
Seemed to work on my end for a few simple cases. @mathiasklenk @jferrettiboke still getting the issue?

**Comment by jferrettiboke** [comment] 2022-11-01 16:48
@keonik Unfortunately, it doesn't work. I'm still getting the same issue. These are my dependencies.

```
{
  ...
  "dependencies": {
    ...
    "@prisma/client": "^4.5.0"
  },
  "devDependencies": {
    ...
    "@mermaid-js/mermaid-cli": "^9.1.7",
    "prisma": "^4.5.0",
    "prisma-erd-generator": "^1.2.2"
  }
}
```

Could it be related with `mmdc` instead? The error says that the command failed.

**Comment by magnokf** [comment] 2022-11-02 14:12
Still without solution 

 npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Command failed: /home/magnokf/rocketseat/ignite/nlw/copa/server/node_modules/.bin/mmdc -i /tmp/prisma-erd-rxQgJh/prisma.mmd -o /home/magnokf/rocketseat/ignite/nlw/copa/server/prisma/ERD.svg -t forest -c /tmp/prisma-erd-rxQgJh/config.json

**Comment by keonik** [comment] 2022-11-02 18:41
Okay next guess is to go through the OS and node versions to see if you are one of the current issues around mmdc and mermaid with Windows

**Comment by mcatel** [comment] 2022-11-02 20:20
I changed the prisma-erd-generator version to 1.2.1 and it worked again

**Comment by mathiasklenk** [comment] 2022-11-03 07:26
It's weird, the last few days it worked again. So it's kinda a bit unpredicted I must say. What fixed the issue was always to completely remove the library and mmdc and then reading it fresh back. Don't know if that helps though!

**Comment by johncblandii** [comment] 2022-11-03 18:03
I got the same `mmdc` error and I resolved it by deleting `node_modules` for a fresh install.

**Comment by jferrettiboke** [comment] 2022-11-03 18:10
@johncblandii That didn't work for me. I tried that multiple times without any luck. The error seems to be consistent across environments (development/localhost, production/localhost, previews/Vercel, production/Vercel).

@keonik BTW, I don't know if this could be related or not, but I have a monorepo setup. Mentioning this just in case.

**Comment by pmdpaula** [comment] 2022-11-04 19:51
I've tried everything above and what worked for me was:
`sudo apt-get install libxkbcommon-x11-0`

I'm using Win10 WSL2 Ubuntu22.02
Node v18.12.0

**Comment by itaitan** [comment] 2022-11-06 01:20
I got the same problem, 
i don`t what to do...
no resolution so far

**Comment by keonik** [comment] 2022-11-09 04:43
Keep sharing OS and Node versions. Thus far it’s been mermaid issues with a few OS’s. As a fallback I believe running a .md file as the output can bypass a script related to this issue.

**Comment by keonik** [comment] 2022-11-09 04:46
Related to #123

**Comment by JNotelddim** [comment] 2022-11-09 23:39
First, sorry for all the duplicate "JNotelddim added a commit that referenced this issue" items 🙈 
I was force-pushing that branch after rebasing and didn't realize it'd affect this Issue thread.

Anyways, that aside:

## Environment

I'm on MacOS Monterey (v12.4) with an M1 chip.

I'm working with `prisma@4.5.0`, and `prisma-erd-generator@1.2.3` (as a dev dependency), node version: `18.12.0`

## Problem

When I try to `prisma generate`, I'm seeing this error:
```
#0 1.417 $ prisma generate                                                                                                                                                     
#0 17.29 Environment variables loaded from .env                                                                                                                                
#0 17.31 Prisma schema loaded from prisma/schema.prisma                                                                                                                        
#0 37.05 Error: 
#0 37.05 ✔ Generated Prisma Client (4.5.0 | library) to ./node_modules/@prisma/client in 459ms
#0 37.05 
#0 37.05 Command failed: /usr/src/app/node_modules/.bin/mmdc -i /tmp/prisma-erd-MGInAL/prisma.mmd -o /usr/src/app/prisma/ERD.svg -t forest -c /tmp/prisma-erd-MGInAL/config.json
#0 37.05 
#0 37.05 
#0 37.13 error Command failed with exit code 1.
#0 37.14 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
(looks like the same `mmdc` issue that others are mentioning)

If i delete `node_modules` and reinstall, it does succeed -- however,
When I try to build this app with docker, even if I add steps in my dockerfile to manually clear the `node_modules` and reinstall the packages, I still see the error.

____

So it is manageable for local development, but I'm needing a solution for building a docker image of my app.
I'm thinking of trying adding a `yarn remove prisma-erd-generator` step in the Dockerfile so that the image would be built without the package, but there's still an issue of how to remove the `generator erd {   provider = "prisma-erd-generator" }` section of the `schema.prisma`.

Anyways if anyone has a solution feel free to let me know :)

**Comment by keonik** [comment] 2022-11-10 05:28
> First, sorry for all the duplicate "JNotelddim added a commit that referenced this issue" items 🙈 I was force-pushing that branch after rebasing and didn't realize it'd affect this Issue thread.
> 
> Anyways, that aside:
> 
> ## Environment
> I'm on MacOS Monterey (v12.4) with an M1 chip.
> 
> I'm working with `prisma@4.5.0`, and `prisma-erd-generator@1.2.3` (as a dev dependency), node version: `18.12.0`
> 
> ## Problem
> When I try to `prisma generate`, I'm seeing this error:
> 
> ```
> #0 1.417 $ prisma generate                                                                                                                                                     
> #0 17.29 Environment variables loaded from .env                                                                                                                                
> #0 17.31 Prisma schema loaded from prisma/schema.prisma                                                                                                                        
> #0 37.05 Error: 
> #0 37.05 ✔ Generated Prisma Client (4.5.0 | library) to ./node_modules/@prisma/client in 459ms
> #0 37.05 
> #0 37.05 Command failed: /usr/src/app/node_modules/.bin/mmdc -i /tmp/prisma-erd-MGInAL/prisma.mmd -o /usr/src/app/prisma/ERD.svg -t forest -c /tmp/prisma-erd-MGInAL/config.json
> #0 37.05 
> #0 37.05 
> #0 37.13 error Command failed with exit code 1.
> #0 37.14 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> (looks like the same `mmdc` issue that others are mentioning)
> 
> If i delete `node_modules` and reinstall, it does succeed -- however, When I try to build this app with docker, even if I add steps in my dockerfile to manually clear the `node_modules` and reinstall the packages, I still see the error.
> 
> So it is manageable for local development, but I'm needing a solution for building a docker image of my app. I'm thinking of trying adding a `yarn remove prisma-erd-generator` step in the Dockerfile so that the image would be built without the package, but there's still an issue of how to remove the `generator erd { provider = "prisma-erd-generator" }` section of the `schema.prisma`.
> 
> Anyways if anyone has a solution feel free to let me know :)

Others use the disable flag to skip the ERD in docker.

**Comment by keonik** [comment] 2022-11-10 05:28
https://github.com/keonik/prisma-erd-generator#disabled

**Comment by JNotelddim** [comment] 2022-11-10 18:11
>Others use the disable flag to skip the ERD in docker.

Ahh beautiful, thanks 🙏

**Comment by lokize** [comment] 2022-12-03 13:02
I still have this problem only work with md extension when i try using png, pdf or svg not worked.

**Comment by keonik** [comment] 2023-03-21 19:19
> It's weird, the last few days it worked again. So it's kinda a bit unpredictable I must say. What fixes the issue temporarily was to completely remove the library and also @mermaid-js/mermaid-cli and then installing it again. Don't know if that helps though!

Closing after finding this out. I believe the issue was an upgrade in mermaid going from v8 to v9. The alpha release which is v.1.3.0 of this repository is updated to version 10. Give it a try and let me know if this issue persists.

**Closed by keonik** 2023-03-21 19:19 UTC
